
1) Generate a tuple from the set ["aman", "222", 777, 400.4] 



In [ ]:
tuple1 = tuple(["aman", "222", 777, 400.4])
print(tuple1)


2) Create a dictionary of your basic data: (a) Roll No (b) Last Name (c) First Name (d) Date of birth. Print out the values and keys. 

In [2]:

dict1 = {"Roll No": "222", "Last Name": "Kumar", "First Name": "Aman", "Date of birth": "01/01/1999"}
print(dict1)

{'Roll No': '222', 'Last Name': 'Kumar', 'First Name': 'Aman', 'Date of birth': '01/01/1999'}


3) Use rand function to generate a 2-dimensional random array with seed. 

In [6]:
import numpy as np

np.random.seed(1)
arr = np.random.randint(10, size=(3, 3))
print(arr)

[[5 8 9]
 [5 0 0]
 [1 7 6]]


4) Generate a single random number in [0.0, 1.0]. Find the absolute value of (-1234) 

In [8]:
import random
print(random.random())
print(abs(-1234))

0.19891353835925907
1234


5) Return a random integer N such that 20 <= N <= 90.  

In [10]:
import numpy as np
new = np.random.randint(20,90)
print(new)

45


6) Given a population or set[11, 12, 13,14, 15] 

Return a 3 length list of unique elements without replacement. 

Shuffle the above set 

Print a random number from the set 

In [21]:
from random import shuffle
import numpy as np
import math

pop = set([11, 12, 13,14, 15])
print(np.random.choice(list(pop), 3, replace=False))
print(np.random.choice(list(pop), 1))





[13 15 14]
[14]


7) Write the text "The King is Dead, Long Live The King" on to a file in your hard drive; read and print the text. 

In [27]:
with open("E:\Workspace\Rough\DS\see.txt", "w") as f:
    f.write("The King is Dead, Long Live The King")


8) Create an illustrative function to demonstrate use of: if, elif and else (b) for, while, break and continue


In [ ]:
def func():
    for i in range(1, 10):
        if i == 5:
            break
        elif i==6:
            continue
        else:
            print("die")
        print(i)
    print("Done")

func()

9) Given a string "The King is Dead, Long Live The King"  

Print the complete string 

Print first character of the string 

Print characters starting from 3rd to 5th 

Print string starting from 3rd character 

Split the words 

In [28]:

str = "The King is Dead, Long Live The King"

print(str)

print(str[0])

print(str[2:5])

print(str[2:])

print(str.split(" "))


The King is Dead, Long Live The King
T
e K
e King is Dead, Long Live The King
['The', 'King', 'is', 'Dead,', 'Long', 'Live', 'The', 'King']


10) An array can be created from a list:  Create an array from a list comprising of numbers 1,4,5,8 (treat them as floats).Slice the above array to display first and second elements 

In [29]:
import numpy as np
arr = np.array([1,4,5,8], dtype = float)
print(arr)
print(arr[0:2])

[1. 4. 5. 8.]
[1. 4.]


11) Array slicing works with multiple dimensions in the same way as usual, applying each slice specification as a filter to a specified dimension. Consider two-dimensional array of (1,2,3) and (4,5,6). 
Slice and display the 2nd row. 
Write code to display as array([2., 5.])  
Find the length of the array. 

In [35]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr[1:,])

arr = np.array([[1,2,3],[4,5,6]])
print(arr[0:,1])

print(len(arr))


[[4 5 6]]
[2 5]
2


12)Arrays can be reshaped using tuples that specify new dimensions. Turn a ten-element one-dimensional array into a two-dimensional one whose first axis has five elements and whose second axis has two elements. Obtain the transpose of the array 

In [37]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
sm =arr.reshape(2,5) 
print(sm)
print(sm.T)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


13)Create an array from a list of 1,2 and 3. 

In [39]:
import numpy
li = [1,2,3]
arr = np.array(li)
print(arr)

[1 2 3]


13)Fill an array [1,2,3] with a single value [9,9,9].  

In [40]:
import numpy as np
arr = np.array([1,2,3])
arr.fill(9)
print(arr)


15) Sum the elements of array [2,4,5]

In [ ]:
import numpy  as np
arr = np.array([2,4,5])
print(arr.sum())



16)Give the products of array [77,74,75] 

In [42]:
import numpy as np 
arr = np.array([77,74,75])
print(arr.prod())

427350


17)Given an array [2,1,9,1,2,22,1,1,4,55,6,2,56]. Find mean, variance, max, min, argmin, median, argmax and standard deviation.


In [43]:
import numpy as np
arr = np.array([2, 1, 9, 1, 2, 22, 1, 1, 4, 55, 6, 2, 56])
print(arr.max())
print(arr.min())
print(arr.mean())
print(arr.std())
print(arr.var())
print(arr.argmax())
print(arr.argmin())


56
1
12.461538461538462
19.165736192147232
367.32544378698225
12
1


 18) Extract unique elements from an array: [1, 1, 4, 5, 5, 5, 7] and sort it.

In [44]:
import numpy as np
arr = np.array([1, 1, 4, 5, 5, 5, 7])
print(np.unique(arr))


[1 4 5 7]


19)Find dot product of two arrays [1, 2, 3]and [0, 1, 1].


In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([0, 1, 1])
print(np.dot(arr1, arr2))

20) Find the eigenvalues and eigenvectors of matrix A

In [48]:
import numpy as np
from numpy.linalg import eig
A = np.array([[1, 2], [3, 4]])
w, v = eig(A)
print(w)
print(v)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


21)Given an array with [11, 22, 11, 31], [25, 33, 31, 28]]. Treat as floats. Find the correlation coefficients.

In [ ]:
import numpy as np
arr1 = np.array([11, 22, 11, 31])
arr2 = np.array([25, 33, 31, 28])
print(np.corrcoef(arr1, arr2))
